import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "~/components/ui/Nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Trash",
  description: "Generated by David Miller",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`flex flex-col justify-center font-sans ${inter.variable}`}
        >
          <div className="m-auto w-full max-w-3xl border border-slate-200">
            <Nav />
            <div className="p-4">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
