import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Separator } from "~/components/ui/separator";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import Nav from "~/components/ui/Nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Trash",
  description: "Generated by David Miller",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`flex justify-center font-sans ${inter.variable}`}>
          <div className="w-full max-w-7xl">
            <Nav />
            <Separator className="mb-4 opacity-50" />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
